config/routes.rb
  Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"

  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates_uniqueness_of :cocktail, scope: :ingredient


end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])

    @dose.cocktail = @cocktail

    if @dose.save!
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy

    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="banner">
  <h3>DASHBOARD</h3>
  <%=image_tag("drink.png" , style: 'height: 50px; width: 50px; margin: 20px;') %>
</div>

<% @cocktails.each do |cocktail| %>
  <div class="card">
    <div class="cocktail_card">
        <%= cl_image_tag cocktail.photo.key, height: 100, width: 100, crop: :fill %>
        <div class="cocktail_card_text">
          <h5><%= link_to cocktail.name, cocktail, style: "color: #2B2D42;" %></h5>
          <p>Some quick example text to build on the card title.</p>
          <i class="fas fa-star" style="color: #5ACCB3; "></i><i class="fas fa-star" style="color: #5ACCB3; "></i><i class="fas fa-star" style="color: #5ACCB3; "></i><i class="fas fa-star" style="color: #5ACCB3; "></i><i class="fas fa-star" style="color: #5ACCB3; "></i>
      </div>
    </div>
  </div>
<% end %>

<p></p>

<div class="button">
  <%= link_to "Add cocktail", new_cocktail_path, style: "color: white; text-decoration: none;"%>
</div>

app/views/cocktails/new.html.erb
<div class="banner">
  <h3>Cocktail</h3>
  <%=image_tag("drink.png" , style: 'height: 50px; width: 50px; margin: 20px;') %>
</div>

<div class="new_cocktail">
  <%= simple_form_for(@cocktail) do |f| %>
    <%= f.label :name, stlye: "font-family: 'Poppins', sans-serif;" %>
    <%= f.text_field :name, stlye: "font-family: 'Poppins', sans-serif;"%>
    <%= f.input :photo, as: :file, style: "" %>
    <%= f.submit class: 'button', style: "border-color: transparent; width: 260px; margin: 20px 0px;" %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<div class="banner">
  <h3>DETAILS </h3>
  <%=image_tag("drink.png" , style: 'height: 50px; width: 50px; margin: 20px;') %>
</div>

<div class="show_title">
  <%= @cocktail.name  %>
</div>

<div class="card_big">
  <div class="cocktail_card">
      <%= cl_image_tag @cocktail.photo.key, height: 150, width: 150, crop: :fill %>
        <div class="cocktail_card_text">
          <p>Please find the detailed description with all ingredients below:</p>
          <ul class="">
            <% @cocktail.doses.each do |dose| %>
              <li class="">
                <p>Description: <%= dose.description %> - Ingredient: <%= dose.ingredient.name %>

                <%= link_to "🗑",
                            dose_path(dose.id),
                            method: :delete,
                            data: { confirm: "Are you sure?" } %> </p>
              </li>
            <% end %>
          </ul>
        </div>
  </div>
  <%= link_to "+ New dose", new_cocktail_dose_path(@cocktail.id), style: "color: #5ACCB3; text-decoration: none;" %>
</div>





<div class="button">
  <%= link_to "List of Cocktails", cocktails_path,style: "color: white; text-decoration: none;"  %>
</div>

app/views/doses/new.html.erb
<div class="banner">
  <h3>INGREDIENT</h3>
  <%=image_tag("drink.png" , style: 'height: 50px; width: 50px; margin: 20px;') %>
</div>

<div class="new_cocktail">
    <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description, stlye: "font-family: 'Poppins', sans-serif;" %>
    <%= f.association :ingredient, stlye: "font-family: 'Poppins', sans-serif;" %>
    <%= f.button :submit, style: "border-color: transparent; width: 260px; margin: 20px 0px;"%>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <!-- <img src="https://www.maxim.com/.image/t_share/MTUwODg5MTM1MDY0NzU0MDA5/cocktails-promo.jpg" style="height: 600px; width: 100%;"alt=""> -->
    </div>
    <%= yield %>


  <div class="footer">
    <div>
      <%= link_to image_tag("search.png", style:"width: 40px; height: 40px;"), cocktails_path %>
      <p>Search</p>
    </div>
    <div>
      <%= link_to image_tag("drink.png", style:"width: 50px; height: 50px;"), cocktails_path %>
    </div>
    <div>
      <%= link_to image_tag("heart.png", style:"width: 40px; height: 40px;"), cocktails_path %>
      <p>My Favs</p>
    </div>
  </div>

  </body>
</html>